version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamotest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-164budlvmruur"
s3_prefix = "dynamotest"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
